
export const NOTICE_MESSAGE_CLOSE = 'NOTICE_MESSAGE_CLOSE'
export const NOTICE_MESSAGE_OPEN = 'NOTICE_MESSAGE_OPEN'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'
// xhr
export const LOADING_DATA = 'LOADING_DATA'
export const RECEIVED_DATA = 'RECEIVED_DATA'
export const RECEIVED_DATA_NOTICE = 'RECEIVED_DATA_NOTICE'
export const LOST_DATA = 'LOST_DATA'



